// Code generated by protoc-gen-go. DO NOT EDIT.
// source: MinerStruct.proto

package mine_intf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 矿池列表请求参数
type MinerListRequest struct {
	FilterField          *FilterField `protobuf:"bytes,1,opt,name=filter_field,json=filterField,proto3" json:"filter_field,omitempty"`
	Page                 int32        `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             int32        `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *MinerListRequest) Reset()         { *m = MinerListRequest{} }
func (m *MinerListRequest) String() string { return proto.CompactTextString(m) }
func (*MinerListRequest) ProtoMessage()    {}
func (*MinerListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_72d271778c39ce88, []int{0}
}

func (m *MinerListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MinerListRequest.Unmarshal(m, b)
}
func (m *MinerListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MinerListRequest.Marshal(b, m, deterministic)
}
func (m *MinerListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MinerListRequest.Merge(m, src)
}
func (m *MinerListRequest) XXX_Size() int {
	return xxx_messageInfo_MinerListRequest.Size(m)
}
func (m *MinerListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MinerListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MinerListRequest proto.InternalMessageInfo

func (m *MinerListRequest) GetFilterField() *FilterField {
	if m != nil {
		return m.FilterField
	}
	return nil
}

func (m *MinerListRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *MinerListRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type FilterField struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status               int32    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Type                 int32    `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	UserId               int32    `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PoolTypeId           string   `protobuf:"bytes,5,opt,name=pool_type_id,json=poolTypeId,proto3" json:"pool_type_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FilterField) Reset()         { *m = FilterField{} }
func (m *FilterField) String() string { return proto.CompactTextString(m) }
func (*FilterField) ProtoMessage()    {}
func (*FilterField) Descriptor() ([]byte, []int) {
	return fileDescriptor_72d271778c39ce88, []int{1}
}

func (m *FilterField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilterField.Unmarshal(m, b)
}
func (m *FilterField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilterField.Marshal(b, m, deterministic)
}
func (m *FilterField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilterField.Merge(m, src)
}
func (m *FilterField) XXX_Size() int {
	return xxx_messageInfo_FilterField.Size(m)
}
func (m *FilterField) XXX_DiscardUnknown() {
	xxx_messageInfo_FilterField.DiscardUnknown(m)
}

var xxx_messageInfo_FilterField proto.InternalMessageInfo

func (m *FilterField) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *FilterField) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *FilterField) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *FilterField) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *FilterField) GetPoolTypeId() string {
	if m != nil {
		return m.PoolTypeId
	}
	return ""
}

// 矿池列表返回
type MinerListResponse struct {
	Code                 ErrorCode    `protobuf:"varint,1,opt,name=code,proto3,enum=mine_intf.ErrorCode" json:"code,omitempty"`
	Data                 []*MinerItem `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *MinerListResponse) Reset()         { *m = MinerListResponse{} }
func (m *MinerListResponse) String() string { return proto.CompactTextString(m) }
func (*MinerListResponse) ProtoMessage()    {}
func (*MinerListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_72d271778c39ce88, []int{2}
}

func (m *MinerListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MinerListResponse.Unmarshal(m, b)
}
func (m *MinerListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MinerListResponse.Marshal(b, m, deterministic)
}
func (m *MinerListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MinerListResponse.Merge(m, src)
}
func (m *MinerListResponse) XXX_Size() int {
	return xxx_messageInfo_MinerListResponse.Size(m)
}
func (m *MinerListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MinerListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MinerListResponse proto.InternalMessageInfo

func (m *MinerListResponse) GetCode() ErrorCode {
	if m != nil {
		return m.Code
	}
	return ErrorCode_SUCCESS
}

func (m *MinerListResponse) GetData() []*MinerItem {
	if m != nil {
		return m.Data
	}
	return nil
}

type MinerItem struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status               int32    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Type                 int32    `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	UserId               int32    `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PoolTypeId           string   `protobuf:"bytes,5,opt,name=pool_type_id,json=poolTypeId,proto3" json:"pool_type_id,omitempty"`
	FriendlyId           int32    `protobuf:"varint,6,opt,name=friendly_id,json=friendlyId,proto3" json:"friendly_id,omitempty"`
	Name                 string   `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	Class                int32    `protobuf:"varint,8,opt,name=class,proto3" json:"class,omitempty"`
	Abbreviation         string   `protobuf:"bytes,9,opt,name=abbreviation,proto3" json:"abbreviation,omitempty"`
	MinerCount           int32    `protobuf:"varint,10,opt,name=miner_count,json=minerCount,proto3" json:"miner_count,omitempty"`
	MinerAmount          float64  `protobuf:"fixed64,11,opt,name=miner_amount,json=minerAmount,proto3" json:"miner_amount,omitempty"`
	AmountCoin           int32    `protobuf:"varint,12,opt,name=amount_coin,json=amountCoin,proto3" json:"amount_coin,omitempty"`
	MinerCoin            float64  `protobuf:"fixed64,13,opt,name=miner_coin,json=minerCoin,proto3" json:"miner_coin,omitempty"`
	BasicYield           float64  `protobuf:"fixed64,14,opt,name=basic_yield,json=basicYield,proto3" json:"basic_yield,omitempty"`
	PresentedYield       float64  `protobuf:"fixed64,15,opt,name=presented_yield,json=presentedYield,proto3" json:"presented_yield,omitempty"`
	AnnualYield          float64  `protobuf:"fixed64,16,opt,name=annual_yield,json=annualYield,proto3" json:"annual_yield,omitempty"`
	Sold                 int32    `protobuf:"varint,17,opt,name=sold,proto3" json:"sold,omitempty"`
	Expires              int64    `protobuf:"varint,18,opt,name=expires,proto3" json:"expires,omitempty"`
	ExitAt               int64    `protobuf:"varint,19,opt,name=exit_at,json=exitAt,proto3" json:"exit_at,omitempty"`
	Duration             int32    `protobuf:"varint,20,opt,name=duration,proto3" json:"duration,omitempty"`
	MiningDate           string   `protobuf:"bytes,21,opt,name=mining_date,json=miningDate,proto3" json:"mining_date,omitempty"`
	MiningLeft           int32    `protobuf:"varint,22,opt,name=mining_left,json=miningLeft,proto3" json:"mining_left,omitempty"`
	MiningCount          int32    `protobuf:"varint,23,opt,name=mining_count,json=miningCount,proto3" json:"mining_count,omitempty"`
	CreatedAt            string   `protobuf:"bytes,24,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,25,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MinerItem) Reset()         { *m = MinerItem{} }
func (m *MinerItem) String() string { return proto.CompactTextString(m) }
func (*MinerItem) ProtoMessage()    {}
func (*MinerItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_72d271778c39ce88, []int{3}
}

func (m *MinerItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MinerItem.Unmarshal(m, b)
}
func (m *MinerItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MinerItem.Marshal(b, m, deterministic)
}
func (m *MinerItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MinerItem.Merge(m, src)
}
func (m *MinerItem) XXX_Size() int {
	return xxx_messageInfo_MinerItem.Size(m)
}
func (m *MinerItem) XXX_DiscardUnknown() {
	xxx_messageInfo_MinerItem.DiscardUnknown(m)
}

var xxx_messageInfo_MinerItem proto.InternalMessageInfo

func (m *MinerItem) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MinerItem) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *MinerItem) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *MinerItem) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *MinerItem) GetPoolTypeId() string {
	if m != nil {
		return m.PoolTypeId
	}
	return ""
}

func (m *MinerItem) GetFriendlyId() int32 {
	if m != nil {
		return m.FriendlyId
	}
	return 0
}

func (m *MinerItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MinerItem) GetClass() int32 {
	if m != nil {
		return m.Class
	}
	return 0
}

func (m *MinerItem) GetAbbreviation() string {
	if m != nil {
		return m.Abbreviation
	}
	return ""
}

func (m *MinerItem) GetMinerCount() int32 {
	if m != nil {
		return m.MinerCount
	}
	return 0
}

func (m *MinerItem) GetMinerAmount() float64 {
	if m != nil {
		return m.MinerAmount
	}
	return 0
}

func (m *MinerItem) GetAmountCoin() int32 {
	if m != nil {
		return m.AmountCoin
	}
	return 0
}

func (m *MinerItem) GetMinerCoin() float64 {
	if m != nil {
		return m.MinerCoin
	}
	return 0
}

func (m *MinerItem) GetBasicYield() float64 {
	if m != nil {
		return m.BasicYield
	}
	return 0
}

func (m *MinerItem) GetPresentedYield() float64 {
	if m != nil {
		return m.PresentedYield
	}
	return 0
}

func (m *MinerItem) GetAnnualYield() float64 {
	if m != nil {
		return m.AnnualYield
	}
	return 0
}

func (m *MinerItem) GetSold() int32 {
	if m != nil {
		return m.Sold
	}
	return 0
}

func (m *MinerItem) GetExpires() int64 {
	if m != nil {
		return m.Expires
	}
	return 0
}

func (m *MinerItem) GetExitAt() int64 {
	if m != nil {
		return m.ExitAt
	}
	return 0
}

func (m *MinerItem) GetDuration() int32 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *MinerItem) GetMiningDate() string {
	if m != nil {
		return m.MiningDate
	}
	return ""
}

func (m *MinerItem) GetMiningLeft() int32 {
	if m != nil {
		return m.MiningLeft
	}
	return 0
}

func (m *MinerItem) GetMiningCount() int32 {
	if m != nil {
		return m.MiningCount
	}
	return 0
}

func (m *MinerItem) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *MinerItem) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func init() {
	proto.RegisterType((*MinerListRequest)(nil), "mine_intf.MinerListRequest")
	proto.RegisterType((*FilterField)(nil), "mine_intf.FilterField")
	proto.RegisterType((*MinerListResponse)(nil), "mine_intf.MinerListResponse")
	proto.RegisterType((*MinerItem)(nil), "mine_intf.MinerItem")
}

func init() { proto.RegisterFile("MinerStruct.proto", fileDescriptor_72d271778c39ce88) }

var fileDescriptor_72d271778c39ce88 = []byte{
	// 587 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x94, 0xb1, 0x6e, 0xdb, 0x30,
	0x10, 0x86, 0x21, 0x27, 0x76, 0xa2, 0xb3, 0xeb, 0x24, 0x6c, 0x9a, 0xb0, 0x29, 0x82, 0x3a, 0x5e,
	0xea, 0x29, 0x43, 0x3a, 0x75, 0x74, 0xdd, 0x06, 0x30, 0x90, 0x2e, 0x4a, 0x97, 0x4c, 0x02, 0x2d,
	0x9e, 0x0c, 0x02, 0x32, 0xa9, 0x92, 0x54, 0x11, 0x67, 0xe8, 0xd4, 0x87, 0xed, 0x63, 0x14, 0x3c,
	0x4a, 0x6e, 0xf2, 0x04, 0x9d, 0xcc, 0xfb, 0xff, 0xef, 0xee, 0xa8, 0x3b, 0xc9, 0x70, 0xf2, 0x4d,
	0x69, 0xb4, 0xf7, 0xde, 0x36, 0x85, 0xbf, 0xae, 0xad, 0xf1, 0x86, 0xa5, 0x1b, 0xa5, 0x31, 0x57,
	0xda, 0x97, 0x17, 0x47, 0x9f, 0x85, 0xc3, 0x85, 0xd1, 0xae, 0xf5, 0xa6, 0xbf, 0xe0, 0x98, 0x12,
	0xee, 0x94, 0xf3, 0x19, 0xfe, 0x68, 0xd0, 0x79, 0xf6, 0x09, 0x46, 0xa5, 0xaa, 0x3c, 0xda, 0xbc,
	0x54, 0x58, 0x49, 0x9e, 0x4c, 0x92, 0xd9, 0xf0, 0xe6, 0xec, 0x7a, 0x57, 0xe6, 0xfa, 0x96, 0xec,
	0xdb, 0xe0, 0x66, 0xc3, 0xf2, 0x5f, 0xc0, 0x18, 0xec, 0xd7, 0x62, 0x8d, 0xbc, 0x37, 0x49, 0x66,
	0xfd, 0x8c, 0xce, 0xec, 0x1d, 0xa4, 0xe1, 0x37, 0x77, 0xea, 0x09, 0xf9, 0x1e, 0x19, 0x87, 0x41,
	0xb8, 0x57, 0x4f, 0x38, 0xfd, 0x9d, 0xc0, 0xf0, 0x59, 0x35, 0x36, 0x86, 0x9e, 0x8a, 0x1d, 0xd3,
	0xac, 0xa7, 0x24, 0x3b, 0x83, 0x81, 0xf3, 0xc2, 0x37, 0xae, 0x2d, 0xd9, 0x46, 0xa1, 0x91, 0xdf,
	0xd6, 0x5d, 0x3d, 0x3a, 0xb3, 0x73, 0x38, 0x68, 0x1c, 0xda, 0x5c, 0x49, 0xbe, 0x1f, 0xe1, 0x10,
	0x2e, 0x25, 0x9b, 0xc0, 0xa8, 0x36, 0xa6, 0xca, 0x03, 0x15, 0xdc, 0x3e, 0x95, 0x87, 0xa0, 0x7d,
	0xdf, 0xd6, 0xb8, 0x94, 0xd3, 0x75, 0x3b, 0xb7, 0x38, 0x06, 0x57, 0x1b, 0xed, 0x90, 0xcd, 0x60,
	0xbf, 0x30, 0x12, 0xe9, 0x36, 0xe3, 0x9b, 0xd3, 0x67, 0xcf, 0xff, 0xd5, 0x5a, 0x63, 0x17, 0x46,
	0x62, 0x46, 0x44, 0x20, 0xa5, 0xf0, 0x82, 0xf7, 0x26, 0x7b, 0xb3, 0xe1, 0x0b, 0x92, 0xaa, 0x2e,
	0x3d, 0x6e, 0x32, 0x22, 0xa6, 0x7f, 0xfa, 0x90, 0xee, 0xb4, 0xff, 0xf4, 0xb4, 0xec, 0x3d, 0x0c,
	0x4b, 0xab, 0x50, 0xcb, 0x6a, 0x1b, 0x80, 0x01, 0xa5, 0x43, 0x27, 0x2d, 0x69, 0x8d, 0x5a, 0x6c,
	0x90, 0x1f, 0x50, 0x2a, 0x9d, 0xd9, 0x29, 0xf4, 0x8b, 0x4a, 0x38, 0xc7, 0x0f, 0x09, 0x8f, 0x01,
	0x9b, 0xc2, 0x48, 0xac, 0x56, 0x16, 0x7f, 0x2a, 0xe1, 0x95, 0xd1, 0x3c, 0xa5, 0x8c, 0x17, 0x5a,
	0x68, 0x17, 0x06, 0x62, 0xf3, 0xc2, 0x34, 0xda, 0x73, 0x88, 0xed, 0x48, 0x5a, 0x04, 0x85, 0x5d,
	0xc1, 0x28, 0x02, 0x62, 0x43, 0xc4, 0x70, 0x92, 0xcc, 0x92, 0x2c, 0x26, 0xcd, 0x49, 0x0a, 0x35,
	0xa2, 0x99, 0x17, 0x46, 0x69, 0x3e, 0x8a, 0x35, 0xa2, 0xb4, 0x30, 0x4a, 0xb3, 0x4b, 0x80, 0xae,
	0x89, 0xd2, 0xfc, 0x15, 0x55, 0x48, 0xdb, 0x1e, 0x8a, 0xee, 0xb0, 0x12, 0x4e, 0x15, 0xf9, 0x96,
	0x5e, 0xe9, 0x31, 0xf9, 0x40, 0xd2, 0x03, 0xbd, 0x78, 0x1f, 0xe0, 0xa8, 0xb6, 0xe8, 0x50, 0x7b,
	0x94, 0x2d, 0x74, 0x44, 0xd0, 0x78, 0x27, 0x47, 0xf0, 0x0a, 0x46, 0x42, 0xeb, 0x46, 0x54, 0x2d,
	0x75, 0x1c, 0x2f, 0x1b, 0xb5, 0x87, 0xee, 0x2b, 0x70, 0xa6, 0x92, 0xfc, 0x24, 0xae, 0x2b, 0x9c,
	0x19, 0x87, 0x03, 0x7c, 0xac, 0x95, 0x45, 0xc7, 0xd9, 0x24, 0x99, 0xed, 0x65, 0x5d, 0x18, 0x16,
	0x89, 0x8f, 0xca, 0xe7, 0xc2, 0xf3, 0xd7, 0xe4, 0x0c, 0x42, 0x38, 0xf7, 0xec, 0x02, 0x0e, 0x65,
	0x63, 0xe3, 0x5c, 0x4f, 0xe3, 0x77, 0xd3, 0xc5, 0xed, 0x4c, 0x95, 0x5e, 0xe7, 0x52, 0x78, 0xe4,
	0x6f, 0xe2, 0x8e, 0xa3, 0xf4, 0x45, 0x78, 0x7c, 0x06, 0x54, 0x58, 0x7a, 0x7e, 0xb6, 0x1b, 0xba,
	0xd2, 0xeb, 0x3b, 0x2c, 0xbb, 0xa1, 0x07, 0x20, 0xae, 0xe5, 0x9c, 0x88, 0x36, 0x29, 0xee, 0xe5,
	0x12, 0xa0, 0xb0, 0x28, 0xc2, 0x44, 0x84, 0xe7, 0x9c, 0x7a, 0xa4, 0xad, 0x32, 0x27, 0xbb, 0xa9,
	0x65, 0x67, 0xbf, 0x8d, 0x76, 0xab, 0xcc, 0xfd, 0x6a, 0x40, 0xff, 0x30, 0x1f, 0xff, 0x06, 0x00,
	0x00, 0xff, 0xff, 0x5a, 0x57, 0x20, 0x58, 0x92, 0x04, 0x00, 0x00,
}
